#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/sail bin phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com phpstan. Arrume antes de continuar... 😎";
    exit 1;
fi;

# Rodar os testes
./vendor/bin/sail pest --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😎";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/sail pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
